export const resumeTemplates = [
    { id: 1, sectionOrder: ["SKILLS", "PROJECTS", "EXPERIENCE", "EDUCATION"] },
    { id: 2, sectionOrder: ["SKILLS", "PROJECTS", "EDUCATION", "EXPERIENCE"] },
    { id: 3, sectionOrder: ["SKILLS", "EXPERIENCE", "PROJECTS", "EDUCATION"] },
    { id: 4, sectionOrder: ["SKILLS", "EXPERIENCE", "EDUCATION", "PROJECTS"] },
    { id: 5, sectionOrder: ["SKILLS", "EDUCATION", "PROJECTS", "EXPERIENCE"] },
    { id: 6, sectionOrder: ["SKILLS", "EDUCATION", "EXPERIENCE", "PROJECTS"] },
    { id: 7, sectionOrder: ["PROJECTS", "SKILLS", "EXPERIENCE", "EDUCATION"] },
    { id: 8, sectionOrder: ["PROJECTS", "SKILLS", "EDUCATION", "EXPERIENCE"] },
    { id: 9, sectionOrder: ["PROJECTS", "EXPERIENCE", "SKILLS", "EDUCATION"] },
    { id: 10, sectionOrder: ["PROJECTS", "EXPERIENCE", "EDUCATION", "SKILLS"] },
    { id: 11, sectionOrder: ["PROJECTS", "EDUCATION", "SKILLS", "EXPERIENCE"] },
    { id: 12, sectionOrder: ["PROJECTS", "EDUCATION", "EXPERIENCE", "SKILLS"] },
    { id: 13, sectionOrder: ["EXPERIENCE", "SKILLS", "PROJECTS", "EDUCATION"] },
    { id: 14, sectionOrder: ["EXPERIENCE", "SKILLS", "EDUCATION", "PROJECTS"] },
    { id: 15, sectionOrder: ["EXPERIENCE", "PROJECTS", "SKILLS", "EDUCATION"] },
    { id: 16, sectionOrder: ["EXPERIENCE", "PROJECTS", "EDUCATION", "SKILLS"] },
    { id: 17, sectionOrder: ["EXPERIENCE", "EDUCATION", "SKILLS", "PROJECTS"] },
    { id: 18, sectionOrder: ["EXPERIENCE", "EDUCATION", "PROJECTS", "SKILLS"] },
    { id: 19, sectionOrder: ["EDUCATION", "SKILLS", "PROJECTS", "EXPERIENCE"] },
    { id: 20, sectionOrder: ["EDUCATION", "SKILLS", "EXPERIENCE", "PROJECTS"] },
    { id: 21, sectionOrder: ["EDUCATION", "PROJECTS", "SKILLS", "EXPERIENCE"] },
    { id: 22, sectionOrder: ["EDUCATION", "PROJECTS", "EXPERIENCE", "SKILLS"] },
    { id: 23, sectionOrder: ["EDUCATION", "EXPERIENCE", "SKILLS", "PROJECTS"] },
    { id: 24, sectionOrder: ["EDUCATION", "EXPERIENCE", "PROJECTS", "SKILLS"] },
];
